# Generated by Django 2.0.2 on 2018-07-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_medium'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofileinfo',
            name='is_user',
            field=models.CharField(default=False, max_length=30),
        ),
    ]
