# Generated by Django 2.0.2 on 2018-07-02 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_sellerprofileinfo_is_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerprofileinfo',
            name='is_user',
        ),
    ]
