# Generated by Django 2.0.2 on 2018-07-03 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_remove_sellerprofileinfo_is_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medium',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categoryApp.Product'),
        ),
    ]
