# Generated by Django 2.0.2 on 2018-07-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_auto_20180703_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medium',
            name='product_id',
            field=models.IntegerField(),
        ),
    ]
