# Generated by Django 2.0.2 on 2018-07-04 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0007_auto_20180703_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerprofileinfo',
            name='user_seller',
        ),
        migrations.DeleteModel(
            name='SellerProfileInfo',
        ),
    ]
