# Generated by Django 2.0.2 on 2018-07-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0008_auto_20180704_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='medium',
            name='title',
            field=models.CharField(default='Laptop', max_length=120),
        ),
    ]
