# Generated by Django 2.0.2 on 2018-05-08 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categoryApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptops',
            name='launch_date',
        ),
        migrations.RemoveField(
            model_name='smartphones',
            name='launch_date',
        ),
    ]
