# Generated by Django 2.0.2 on 2018-05-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoryApp', '0002_auto_20180508_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphones',
            name='image',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
    ]
