# Generated by Django 2.0.2 on 2018-06-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoryApp', '0005_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='model',
        ),
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
