# Generated by Django 2.0.2 on 2018-07-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoryApp', '0006_auto_20180615_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
