# Generated by Django 2.0.2 on 2018-07-12 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categoryApp', '0009_auto_20180712_2249'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pro',
        ),
    ]
