# Generated by Django 2.0.2 on 2018-07-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoryApp', '0010_delete_pro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='avc'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.CharField(default='s-123', max_length=200),
        ),
    ]
