# Generated by Django 2.0.2 on 2018-07-12 17:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoryApp', '0011_auto_20180712_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=39.99, max_digits=20, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
