# Generated by Django 2.0.2 on 2018-07-02 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='user',
            new_name='users',
        ),
    ]
