# Generated by Django 2.0.2 on 2018-07-06 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0004_userprofileinfo_is_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='address',
            field=models.CharField(max_length=30),
        ),
    ]
