# Generated by Django 2.0.2 on 2018-07-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cart_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete='cascade', related_name='user', to='userApp.UserProfileInfo'),
        ),
    ]
